orders/urls.py
from django.urls import path
from .views import checkout, orders


urlpatterns = [
    path('checkout/', checkout, name='checkout'),
    path('orders/', orders, name='orders'),
]

webamshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('', include('webamcarts.urls')),
    path('', include('orders.urls')),
    path('', include('accounts.urls')),
] 


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class ProductMen(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=100, default=29.99)
    sale_price = models.DecimalField(decimal_places=2, max_digits=100, null=True, blank=True)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        unique_together = ('title','slug')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # return reverse('mdressdetails', args=[self.slug])
        return reverse('mdressdetails', kwargs={'slug':self.slug})


class ProductMenImage(models.Model):
    productmen = models.ForeignKey(ProductMen, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/images/men')
    menimgalt = models.CharField(max_length=120, null=True, blank=True)
    featured = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.productmen.title


class VariationManager(models.Manager):
    def all(self):
        return super(VariationManager, self).filter(active=True)

    def sizes(self):
        return self.all().filter(category='size')

    def colors(self):
        return self.all().filter(category='color')

VAR_CATEGORIES = (
    ('size','size'),
    ('color','color'),
    ('package','package'),
)

class Variation(models.Model):
    productmen = models.ForeignKey(ProductMen, null=True, blank=True, on_delete=models.CASCADE)
    category = models.CharField(max_length=120, choices=VAR_CATEGORIES, default='size')
    title = models.CharField(max_length=120)
    image = models.ForeignKey(ProductMenImage, on_delete=models.CASCADE, null=True, blank=True)
    price = models.DecimalField(max_digits=1000, decimal_places=2, null=True, blank=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    object = VariationManager()




class ProductWomen(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=100, default=29.99)
    sale_price = models.DecimalField(decimal_places=2, max_digits=100, null=True, blank=True)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        unique_together = ('title','slug')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('femaledressdetails', kwargs={'slug':self.slug})
       

class ProductWomenImage(models.Model):
    productwomen = models.ForeignKey(ProductWomen, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/images/women')
    wmenimgalt = models.CharField(max_length=120, null=True, blank=True)
    featured = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.productwomen.title


class ProductKids(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=100, default=29.99)
    sale_price = models.DecimalField(decimal_places=2, max_digits=100, null=True, blank=True)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        unique_together = ('title','slug')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('kidsdressdetails', kwargs={'slug':self.slug})
       

class ProductKidsImage(models.Model):
    productkids = models.ForeignKey(ProductKids, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/images/kids')
    kidsimgalt = models.CharField(max_length=120, null=True, blank=True)
    featured = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.productkids.title


class ProductAccessory(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=100, default=29.99)
    sale_price = models.DecimalField(decimal_places=2, max_digits=100, null=True, blank=True)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        unique_together = ('title','slug') 

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('accessdressdetails', kwargs={'slug':self.slug})
       

class ProductAccessoriesImage(models.Model):
    productaccessory = models.ForeignKey(ProductAccessory, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/images/accessories')
    accessimgalt = models.CharField(max_length=120, null=True, blank=True)
    featured = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.productaccessory.title

webamcarts/models.py
from django.db import models
from products.models import ProductMen, Variation, ProductWomen, ProductKids, ProductAccessory


class Cartmen(models.Model):
    total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return 'Cart men id: %s' %(self.id)


class CartItem(models.Model):
    cart = models.ForeignKey(Cartmen, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(ProductMen, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation)
    quantity = models.IntegerField(default=1)
    line_total = models.DecimalField(max_digits=1000, decimal_places=2, default=10.99)
    notes = models.TextField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        try:
            return str(self.cart.id)
        except:
            return self.product.title


class Cartwomen(models.Model):
    productwomen = models.ManyToManyField(ProductWomen)
    total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
    titmestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return 'Cart women id: %s' %(self.id)

class Cartkids(models.Model):
    productkids = models.ManyToManyField(ProductKids)
    total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return 'Cart kids id: %s' %(self.id)

class Cartaccessry(models.Model):
    productaccessry = models.ManyToManyField(ProductAccessory)
    total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return 'Cart Accessory id: %s' %(self.id)

templates/cart/viewaccessory.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 

<div class="breadcrumbs">
<div class="container">
<div class="row">
<div class="col-12">
<div class="bread-inner">
<ul class="bread-list">
<li><a href="index1.html">Home<i class="ti-arrow-right"></i></a></li>
<li class="active"><a href="blog-single.html">Cart</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>


<div class="shopping-cart section">
<div class="container">
<div class="row">
<div class="col-12">
<!-- Shopping Summery -->
<table class="table shopping-summery">
<thead>
<tr class="main-hading">
<th>PRODUCT</th>
<th>NAME</th>
<th class="text-center">UNIT PRICE</th>
<th class="text-center">QUANTITY</th>
<th class="text-center">TOTAL</th> 
<th class="text-center"><i class="ti-trash remove-icon"></i></th>
</tr>
</thead>
<tbody>
{% for carvaccessory in cartaccry.productaccessry.all %}

<tr>
<td class="image" data-title="No"><img src="https://via.placeholder.com/100x100" alt="#"></td>
<td class="product-des" data-title="Description">
<p class="product-name"><a href="#">{{ carvaccessory.title }}</a></p>
<br>
<p class="product-des">{{ carvaccessory.description }}</p>
</td>
<td class="price" data-title="Price"><span>${{ carvaccessory.price }} </span></td>
<td class="qty" data-title="Qty"><!-- Input Order -->
<div class="input-group">
<div class="button minus">
<button type="button" class="btn btn-primary btn-number" disabled="disabled" data-type="minus" data-field="quant[1]">
<i class="ti-minus"></i>
</button>
</div>
<input type="text" name="quant[1]" class="input-number" data-min="1" data-max="100" value="1">
<div class="button plus">
<button type="button" class="btn btn-primary btn-number" data-type="plus" data-field="quant[1]">
<i class="ti-plus"></i>
</button>
</div>
</div>
<!--/ End Input Order -->
</td>
<td class="total-amount" data-title="Total"><span>$200</span></td>
<td class="action" data-title="Remove"><a href="#"><i class="ti-trash remove-icon"></i></a></td>
</tr>

{% endfor %}
</tbody>
</table>
<!--/ End Shopping Summery -->
</div>
</div>
<div class="row">
<div class="col-12">
<!-- Total Amount -->
<div class="total-amount">
<div class="row">
<div class="col-lg-8 col-md-5 col-12">
<div class="left">
<div class="coupon">
<form action="#" target="_blank">
<input name="Coupon" placeholder="Enter Your Coupon">
<button class="btn">Apply</button>
</form>
</div>
<div class="checkbox">
<label class="checkbox-inline" for="2"><input name="news" id="2" type="checkbox"> Shipping (+10$)</label>
</div>
</div>
</div>
<div class="col-lg-4 col-md-7 col-12">
<div class="right">
<ul>
<li>Cart Subtotal<span>$330.00</span></li>
<li>Shipping<span>Free</span></li>
<li>You Save<span>$20.00</span></li>
<li class="last">You Pay<span>$310.00</span></li>
</ul>
<div class="button5">
<a href="#" class="btn">Checkout</a>
<a href="#" class="btn">Continue shopping</a>
</div>
</div>
</div>
</div>
</div>
<!--/ End Total Amount -->
</div>
</div>
</div>
</div>

{% endblock %}

templates/cart/viewkids.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 

<div class="breadcrumbs">
<div class="container">
<div class="row">
<div class="col-12">
<div class="bread-inner">
<ul class="bread-list">
<li><a href="index1.html">Home<i class="ti-arrow-right"></i></a></li>
<li class="active"><a href="blog-single.html">Cart</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>


<div class="shopping-cart section">
<div class="container">
<div class="row">
<div class="col-12">
<!-- Shopping Summery -->
<table class="table shopping-summery">
<thead>
<tr class="main-hading">
<th>PRODUCT</th>
<th>NAME</th>
<th class="text-center">UNIT PRICE</th>
<th class="text-center">QUANTITY</th>
<th class="text-center">TOTAL</th> 
<th class="text-center"><i class="ti-trash remove-icon"></i></th>
</tr>
</thead>
<tbody>

{% for cartkview in cartkids.productkids.all %}

<tr>
<td class="image" data-title="No"><img src="https://via.placeholder.com/100x100" alt="#"></td>
<td class="product-des" data-title="Description">
<p class="product-name"><a href="#">{{ cartkview.title }}</a></p>
<br>
<p class="product-des">{{ cartkview.description }}</p>
</td>
<td class="price" data-title="Price"><span>${{ cartkview.price }} </span></td>
<td class="qty" data-title="Qty"><!-- Input Order -->
<div class="input-group">
<div class="button minus">
<button type="button" class="btn btn-primary btn-number" disabled="disabled" data-type="minus" data-field="quant[1]">
<i class="ti-minus"></i>
</button>
</div>
<input type="text" name="quant[1]" class="input-number" data-min="1" data-max="100" value="1">
<div class="button plus">
<button type="button" class="btn btn-primary btn-number" data-type="plus" data-field="quant[1]">
<i class="ti-plus"></i>
</button>
</div>
</div>
<!--/ End Input Order -->
</td>
<td class="total-amount" data-title="Total"><span>$200</span></td>
<td class="action" data-title="Remove"><a href="#"><i class="ti-trash remove-icon"></i></a></td>
</tr>

{% endfor %}
</tbody>
</table>
<!--/ End Shopping Summery -->
</div>
</div>
<div class="row">
<div class="col-12">
<!-- Total Amount -->
<div class="total-amount">
<div class="row">
<div class="col-lg-8 col-md-5 col-12">
<div class="left">
<div class="coupon">
<form action="#" target="_blank">
<input name="Coupon" placeholder="Enter Your Coupon">
<button class="btn">Apply</button>
</form>
</div>
<div class="checkbox">
<label class="checkbox-inline" for="2"><input name="news" id="2" type="checkbox"> Shipping (+10$)</label>
</div>
</div>
</div>
<div class="col-lg-4 col-md-7 col-12">
<div class="right">
<ul>
<li>Cart Subtotal<span>$330.00</span></li>
<li>Shipping<span>Free</span></li>
<li>You Save<span>$20.00</span></li>
<li class="last">You Pay<span>$310.00</span></li>
</ul>
<div class="button5">
<a href="#" class="btn">Checkout</a>
<a href="#" class="btn">Continue shopping</a>
</div>
</div>
</div>
</div>
</div>
<!--/ End Total Amount -->
</div>
</div>
</div>
</div>











{% endblock %}

templates/cart/viewmen.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 

<div class="breadcrumbs">
<div class="container">
<div class="row">
<div class="col-12">
<div class="bread-inner">
<ul class="bread-list">
<li><a href="index1.html">Home<i class="ti-arrow-right"></i></a></li>
<li class="active"><a href="blog-single.html">Cart</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
{% if cartmen_empty %}
<div style="padding:50px 0;background:#F6F7FB;">
<div class="container">
<div class="row">
<div class="col-md-12 text-center">
<h2 style="color: #f7941d;"><i>{{ cart_men_empty_message }}</i></h2>
</div>
</div>
</div>
</div>
{% else %}
<div class="shopping-cart section">
<div class="container">
<div class="row">
<div class="col-12">
<!-- Shopping Summery -->
<table class="table shopping-summery">
<thead>
<tr class="main-hading">
<th>PRODUCT</th>
<th>NAME</th>
<th class="text-center">UNIT PRICE</th>
<th class="text-center">QUANTITY</th>
<th class="text-center">TOTAL</th> 
<th class="text-center"><i class="ti-trash remove-icon"></i></th>
</tr>
</thead>
<tbody>

{% for cartmenv in cartmen.cartitem_set.all %}

<tr>
<td class="image" data-title="No">
{% for crtmenimg in cartmenv.product.productmenimage_set.all %}
{% if crtmenimg.featured %}
<img src="{{ MEDIA_URL }}{{ crtmenimg.image.url }}" alt="{{ crtmenimg.menimgalt }}">
{% else %}
<img src='{% static "images/noimg.jpg" %}' alt="Webam default image">
{% endif %}
{% endfor %}
</td>
<td class="product-des" data-title="Description">
<p class="product-name"><a href="#">{{ cartmenv.product.title }}</a>
{% if cartmenv.variations.all %}
<ul class="listinline">
{% for subitem in cartmenv.variations.all %}
<li><strong>{{ subitem.category|capfirst }}:</strong> {{ subitem.title|capfirst }}</li>
{% endfor %}
</ul>
{% endif %}
</p>
<br>
<p class="product-des">{{ cartmenv.product.description }}</p>
</td>
<td class="price" data-title="Price"><span>${{ cartmenv.product.price }} </span></td>


<td class="qty" data-title="Qty"><!-- Input Order -->
{{ cartmenv.quantity }}
<!-- <div class="input-group">
<div class="button minus">
<button type="button" class="btn btn-primary btn-number" disabled="disabled" data-type="minus" data-field="quant[1]">
<i class="ti-minus"></i>
</button>
</div>
<input type="text" name="quant[1]" class="input-number" data-min="1" data-max="100" value="1">
<div class="button plus">
<button type="button" class="btn btn-primary btn-number" data-type="plus" data-field="quant[1]">
<i class="ti-plus"></i>
</button>
</div>
</div> -->
<!--/ End Input Order -->
</td>
<td class="total-amount" data-title="Total"><span>${{ cartmenv.line_total }}</span></td>

<td class="action" data-title="Remove"><a href="{% url 'remove_from_cart' cartmenv.id %}"><i class="ti-trash remove-icon"></i></a></td>
</tr>

{% endfor %}

</tbody>
</table>
<!--/ End Shopping Summery -->
</div>
</div>
<div class="row">
<div class="col-12">
<!-- Total Amount -->
<div class="total-amount">
<div class="row">
<div class="col-lg-8 col-md-5 col-12">
<div class="left">
<div class="coupon">
<form action="#" target="_blank">
<input name="Coupon" placeholder="Enter Your Coupon">
<button class="btn">Apply</button>
</form>
</div>
<div class="checkbox">
<label class="checkbox-inline" for="2"><input name="news" id="2" type="checkbox"> Shipping (+10$)</label>
</div>
</div>
</div>
<div class="col-lg-4 col-md-7 col-12">
<div class="right">
<ul>
<li>Cart Subtotal<span><strong>${{ cartmen.total }}</strong></span></li>
<li>Shipping<span>Free</span></li>
<li>You Save<span>$20.00</span></li>
<li class="last">You Pay<span>$310.00</span></li>
</ul>
<div class="button5">
<a href="{% url 'checkout' %}" class="btn">Checkout</a>
<a href="#" class="btn">Continue shopping</a>
</div>
</div>
</div>
</div>
</div>
<!--/ End Total Amount -->
</div>
</div>
</div>
</div>

{% endif %}

{% endblock %}

templates/cart/viewomen.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 

<div class="breadcrumbs">
<div class="container">
<div class="row">
<div class="col-12">
<div class="bread-inner">
<ul class="bread-list">
<li><a href="index1.html">Home<i class="ti-arrow-right"></i></a></li>
<li class="active"><a href="blog-single.html">Cart</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>


<div class="shopping-cart section">
<div class="container">
<div class="row">
<div class="col-12">
<!-- Shopping Summery -->
<table class="table shopping-summery">
<thead>
<tr class="main-hading">
<th>PRODUCT</th>
<th>NAME</th>
<th class="text-center">UNIT PRICE</th>
<th class="text-center">QUANTITY</th>
<th class="text-center">TOTAL</th> 
<th class="text-center"><i class="ti-trash remove-icon"></i></th>
</tr>
</thead>
<tbody>

{% for cartwview in cartwomen.productwomen.all %}

<tr>
<td class="image" data-title="No"><img src="https://via.placeholder.com/100x100" alt="#"></td>
<td class="product-des" data-title="Description">
<p class="product-name"><a href="#">{{ cartwview.title }}</a></p>

<br>
<p class="product-des">{{ cartwview.description }}</p>
</td>
<td class="price" data-title="Price"><span>${{ cartwview.price }} </span></td>
<td class="qty" data-title="Qty"><!-- Input Order -->
<div class="input-group">
<div class="button minus">
<button type="button" class="btn btn-primary btn-number" disabled="disabled" data-type="minus" data-field="quant[1]">
<i class="ti-minus"></i>
</button>
</div>
<input type="text" name="quant[1]" class="input-number" data-min="1" data-max="100" value="1">
<div class="button plus">
<button type="button" class="btn btn-primary btn-number" data-type="plus" data-field="quant[1]">
<i class="ti-plus"></i>
</button>
</div>
</div>
<!--/ End Input Order -->
</td>
<td class="total-amount" data-title="Total"><span>$200</span></td>
<td class="action" data-title="Remove"><a href="#"><i class="ti-trash remove-icon"></i></a></td>
</tr>

{% endfor %}
</tbody>
</table>
<!--/ End Shopping Summery -->
</div>
</div>
<div class="row">
<div class="col-12">
<!-- Total Amount -->
<div class="total-amount">
<div class="row">
<div class="col-lg-8 col-md-5 col-12">
<div class="left">
<div class="coupon">
<form action="#" target="_blank">
<input name="Coupon" placeholder="Enter Your Coupon">
<button class="btn">Apply</button>
</form>
</div>
<div class="checkbox">
<label class="checkbox-inline" for="2"><input name="news" id="2" type="checkbox"> Shipping (+10$)</label>
</div>
</div>
</div>
<div class="col-lg-4 col-md-7 col-12">
<div class="right">
<ul>
<li>Cart Subtotal<span>$330.00</span></li>
<li>Shipping<span>Free</span></li>
<li>You Save<span>$20.00</span></li>
<li class="last">You Pay<span>$310.00</span></li>
</ul>
<div class="button5">
<a href="#" class="btn">Checkout</a>
<a href="#" class="btn">Continue shopping</a>
</div>
</div>
</div>
</div>
</div>
<!--/ End Total Amount -->
</div>
</div>
</div>
</div>




{% endblock %}